import fs from "fs";

async function main() {
  const res = await fetch(
    "https://raw.githubusercontent.com/Purukitto/pokemon-data.json/master/pokedex.json",
  );
  const data = await res.json();

  const simplified = data.map((p) => ({
    id: p.id,
    name: p.name.english,
  }));

  const fileContent = `// Generated by scripts/fetch_pokedex.ts
export const POKEDEX = ${JSON.stringify(simplified, null, 2)} as const;

export const POKEDEX_MAP = new Map(POKEDEX.map(p => [p.id, p.name.toLowerCase()]));
`;

  console.log(fileContent);
}

main();
